#!/bin/bash

# Make sure the user data directory is owned by the developer user
if [ -d "/home/developer/.AndroidStudio1.3"]; then
  sudo chown developer:developer /home/developer/.AndroidStudio1.3
fi
exec /opt/android-studio/bin/studio.sh
